# Generated by Django 5.0.3 on 2024-05-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0012_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(through='inventory.RolePermission', to='auth.permission'),
        ),
    ]
